//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceHost
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int Id { get; set; }
        public string nome { get; set; }
        public Nullable<int> enderecoId { get; set; }
        public string cpf { get; set; }
        public string rg { get; set; }
        public string sexo { get; set; }
        public string estadoCivil { get; set; }
        public string orgaoExpedicao { get; set; }
        public Nullable<System.DateTime> dataExpedicao { get; set; }
        public Nullable<System.DateTime> dataNascimento { get; set; }
    
        public virtual EnderecoCliente EnderecoCliente { get; set; }
    }
}
