//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceHost")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebForm.ServiceReference.EnderecoCliente EnderecoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dataExpedicaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dataNascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> enderecoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoCivilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orgaoExpedicaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebForm.ServiceReference.EnderecoCliente EnderecoCliente {
            get {
                return this.EnderecoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoClienteField, value) != true)) {
                    this.EnderecoClienteField = value;
                    this.RaisePropertyChanged("EnderecoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cpf {
            get {
                return this.cpfField;
            }
            set {
                if ((object.ReferenceEquals(this.cpfField, value) != true)) {
                    this.cpfField = value;
                    this.RaisePropertyChanged("cpf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dataExpedicao {
            get {
                return this.dataExpedicaoField;
            }
            set {
                if ((this.dataExpedicaoField.Equals(value) != true)) {
                    this.dataExpedicaoField = value;
                    this.RaisePropertyChanged("dataExpedicao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dataNascimento {
            get {
                return this.dataNascimentoField;
            }
            set {
                if ((this.dataNascimentoField.Equals(value) != true)) {
                    this.dataNascimentoField = value;
                    this.RaisePropertyChanged("dataNascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> enderecoId {
            get {
                return this.enderecoIdField;
            }
            set {
                if ((this.enderecoIdField.Equals(value) != true)) {
                    this.enderecoIdField = value;
                    this.RaisePropertyChanged("enderecoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estadoCivil {
            get {
                return this.estadoCivilField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoCivilField, value) != true)) {
                    this.estadoCivilField = value;
                    this.RaisePropertyChanged("estadoCivil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orgaoExpedicao {
            get {
                return this.orgaoExpedicaoField;
            }
            set {
                if ((object.ReferenceEquals(this.orgaoExpedicaoField, value) != true)) {
                    this.orgaoExpedicaoField = value;
                    this.RaisePropertyChanged("orgaoExpedicao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rg {
            get {
                return this.rgField;
            }
            set {
                if ((object.ReferenceEquals(this.rgField, value) != true)) {
                    this.rgField = value;
                    this.RaisePropertyChanged("rg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                if ((object.ReferenceEquals(this.sexoField, value) != true)) {
                    this.sexoField = value;
                    this.RaisePropertyChanged("sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnderecoCliente", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceHost")]
    [System.SerializableAttribute()]
    public partial class EnderecoCliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string complementoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string logradouroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> numeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ufField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bairro {
            get {
                return this.bairroField;
            }
            set {
                if ((object.ReferenceEquals(this.bairroField, value) != true)) {
                    this.bairroField = value;
                    this.RaisePropertyChanged("bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cep {
            get {
                return this.cepField;
            }
            set {
                if ((object.ReferenceEquals(this.cepField, value) != true)) {
                    this.cepField = value;
                    this.RaisePropertyChanged("cep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cidade {
            get {
                return this.cidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.cidadeField, value) != true)) {
                    this.cidadeField = value;
                    this.RaisePropertyChanged("cidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string complemento {
            get {
                return this.complementoField;
            }
            set {
                if ((object.ReferenceEquals(this.complementoField, value) != true)) {
                    this.complementoField = value;
                    this.RaisePropertyChanged("complemento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string logradouro {
            get {
                return this.logradouroField;
            }
            set {
                if ((object.ReferenceEquals(this.logradouroField, value) != true)) {
                    this.logradouroField = value;
                    this.RaisePropertyChanged("logradouro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> numero {
            get {
                return this.numeroField;
            }
            set {
                if ((this.numeroField.Equals(value) != true)) {
                    this.numeroField = value;
                    this.RaisePropertyChanged("numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string uf {
            get {
                return this.ufField;
            }
            set {
                if ((object.ReferenceEquals(this.ufField, value) != true)) {
                    this.ufField = value;
                    this.RaisePropertyChanged("uf");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IClienteService")]
    public interface IClienteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/DoWork", ReplyAction="http://tempuri.org/IClienteService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/Update", ReplyAction="http://tempuri.org/IClienteService/UpdateResponse")]
        void Update(WebForm.ServiceReference.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/GetById", ReplyAction="http://tempuri.org/IClienteService/GetByIdResponse")]
        WebForm.ServiceReference.Cliente GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/GetAllCliente", ReplyAction="http://tempuri.org/IClienteService/GetAllClienteResponse")]
        WebForm.ServiceReference.Cliente[] GetAllCliente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/Delete", ReplyAction="http://tempuri.org/IClienteService/DeleteResponse")]
        void Delete(WebForm.ServiceReference.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/Insert", ReplyAction="http://tempuri.org/IClienteService/InsertResponse")]
        WebForm.ServiceReference.Cliente Insert(WebForm.ServiceReference.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/GetAllEndereco", ReplyAction="http://tempuri.org/IClienteService/GetAllEnderecoResponse")]
        WebForm.ServiceReference.EnderecoCliente GetAllEndereco();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/GetClienteByName", ReplyAction="http://tempuri.org/IClienteService/GetClienteByNameResponse")]
        WebForm.ServiceReference.Cliente[] GetClienteByName(string nome);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClienteServiceChannel : WebForm.ServiceReference.IClienteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteServiceClient : System.ServiceModel.ClientBase<WebForm.ServiceReference.IClienteService>, WebForm.ServiceReference.IClienteService {
        
        public ClienteServiceClient() {
        }
        
        public ClienteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public void Update(WebForm.ServiceReference.Cliente cliente) {
            base.Channel.Update(cliente);
        }
        
        public WebForm.ServiceReference.Cliente GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public WebForm.ServiceReference.Cliente[] GetAllCliente() {
            return base.Channel.GetAllCliente();
        }
        
        public void Delete(WebForm.ServiceReference.Cliente cliente) {
            base.Channel.Delete(cliente);
        }
        
        public WebForm.ServiceReference.Cliente Insert(WebForm.ServiceReference.Cliente cliente) {
            return base.Channel.Insert(cliente);
        }
        
        public WebForm.ServiceReference.EnderecoCliente GetAllEndereco() {
            return base.Channel.GetAllEndereco();
        }
        
        public WebForm.ServiceReference.Cliente[] GetClienteByName(string nome) {
            return base.Channel.GetClienteByName(nome);
        }
    }
}
